name: CreativeDestruction
favicon: null
layout_spectrum: 0.24856
typography_spectrum: 0.89788
title: CreativeDestruction
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#deddc0'
    - '#2b4745'
    - '#6f9d8d'
    - '#bb8e5e'
    - '#615d53'
  brandStrength: 0.75
  lightness: 0.1800867971032858
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
