name: CreativeDestruction
favicon: null
layout_spectrum: 0.24856
typography_spectrum: 0.89788
title: CreativeDestruction
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#022940'
    - '#5a98a0'
    - '#935e33'
    - '#44463a'
    - '#d68a51'
  brandStrength: 0.75
  lightness: 0.1800867971032858
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
