name: CreativeDestruction
favicon: null
layout_spectrum: 0.76096
typography_spectrum: 0.98795
title: CreativeDestruction
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040c10'
    - '#41494c'
    - '#595f60'
    - '#858583'
    - '#a5a5a5'
  brandStrength: 1
  lightness: 0.625
  saturation: 0.8125
  rhythmicContrast: 1
purpose: []
